// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectGH():Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function Fetch():Promise<void>;

export function GetDiff(arg1:string):Promise<void>;

export function GetPRList():Promise<void>;

export function SearchPRList(arg1:number,arg2:string):Promise<Array<{number:number,title:string,author:string,baseBranch:string}>>;

export function GetCurrentProject():Promise<{name: string, path: string}>;

export function GetRecentProjects():Promise<Array<{name: string, path: string, openedAt: string}>>;

export function OpenProject():Promise<string>;

export function SwitchProject(arg1:string):Promise<void>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function SwitchBranch(arg1:string):Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;

export function Refresh():Promise<void>;
