// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutPR(arg1) {
  return window['go']['main']['App']['CheckoutPR'](arg1);
}

export function CheckoutPRToWorktree(arg1) {
  return window['go']['main']['App']['CheckoutPRToWorktree'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function CreatePR(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePR'](arg1, arg2, arg3, arg4);
}

export function DetectGH() {
  return window['go']['main']['App']['DetectGH']();
}

export function DiscardFile(arg1) {
  return window['go']['main']['App']['DiscardFile'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetDiff(arg1, arg2) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2);
}

export function GetFileContents(arg1, arg2) {
  return window['go']['main']['App']['GetFileContents'](arg1, arg2);
}

export function GetPRComments(arg1) {
  return window['go']['main']['App']['GetPRComments'](arg1);
}

export function GetPRFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetPRFileDiff'](arg1, arg2);
}

export function GetPRFiles(arg1) {
  return window['go']['main']['App']['GetPRFiles'](arg1);
}

export function GetPRList() {
  return window['go']['main']['App']['GetPRList']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetTerminalPrefs() {
  return window['go']['main']['App']['GetTerminalPrefs']();
}

export function GetWorktrees() {
  return window['go']['main']['App']['GetWorktrees']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function PostPRComment(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['PostPRComment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RemoveWorktree(arg1) {
  return window['go']['main']['App']['RemoveWorktree'](arg1);
}

export function SearchPRList(arg1, arg2) {
  return window['go']['main']['App']['SearchPRList'](arg1, arg2);
}

export function SetTerminalPrefs(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalPrefs'](arg1, arg2);
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalStart(arg1) {
  return window['go']['main']['App']['TerminalStart'](arg1);
}

export function TerminalStop(arg1) {
  return window['go']['main']['App']['TerminalStop'](arg1);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}
