// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckoutPR(arg1:number):Promise<void>;

export function CheckoutPRToWorktree(arg1:number):Promise<void>;

export function CreatePR(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DetectGH():Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function Fetch():Promise<void>;

export function GetCurrentProject():Promise<Record<string, string>>;

export function GetDiff(arg1:string):Promise<void>;

export function GetPRComments(arg1:number):Promise<void>;

export function GetPRFileDiff(arg1:number,arg2:string):Promise<void>;

export function GetPRFiles(arg1:number):Promise<void>;

export function GetPRList():Promise<void>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function InvalidatePRCache():Promise<void>;

export function OpenProject():Promise<string>;

export function PostPRComment(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:number,arg7:string):Promise<void>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function Refresh():Promise<void>;

export function SearchPRList(arg1:number,arg2:string):Promise<Array<Record<string, any>>>;

export function StageFile(arg1:string):Promise<void>;

export function SwitchBranch(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;
